apiVersion: v1
kind: List
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app.kubernetes.io/name: hello-java-spring-boot
    name: hello-java-spring-boot
  spec:
    output:
      to:
        kind: DockerImage
        name: docker.io/m1k3dcdc/hello-java-spring-boot:latest
    source:
      # Expect a local directory to be streamed to OpenShift as a build source
      type: Binary
      binary: {}
    strategy:
      type: Docker
      dockerStrategy:
        # Find the image build instructions in ./Dockerfile
        dockerfilePath: Dockerfile
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: hello-java-spring-boot
        app.kubernetes.io/component: hello-java-spring-boot
        app.kubernetes.io/instance: hello-java-spring-boot
      name: hello-java-spring-boot
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: hello-java-spring-boot
      template:
        metadata:
          labels:
            app: hello-java-spring-boot
          name: hello-java-spring-boot
        spec:
          containers:
            - image: docker.io/m1k3pjem/hello-java-spring-boot:latest
              imagePullPolicy: IfNotPresent
              name: hello-java-spring-boot
              env:
                - name: FAVOURITE_CHEESE
                  valueFrom:
                    configMapKeyRef:
                      name: hello-java-spring-boot-configmap
                      key: thefavourite.cheese
              ports:
                - containerPort: 8080
                  protocol: TCP
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: hello-java-spring-boot-service
        app.kubernetes.io/component: hello-java-spring-boot-service
        app.kubernetes.io/instance: hello-java-spring-boot-service
      name: hello-java-spring-boot-service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deployment: hello-java-spring-boot
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: hello-java-spring-boot-route
    spec:
      #host: www.example.com
      #path: /cheese
      port: 8080
      to:
        kind: Service
        name: hello-java-spring-boot-service
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: hello-java-spring-boot-configmap
    data:
      thefavourite.cheese: OAXACA
